[package]
name = "opaque"
version = "0.0.1"
authors = ["gustin <gustin@mycelium.dev>"]
edition = "2018"

[dependencies]
curve25519-dalek = "1.2.3"
blake = "2.0.0"
rand = "0.7.2"
rand_os = "0.1.3"
sha2 = "0.8.0"
x25519-dalek = "0.5.2"
