[package]
name = "opaque"
version = "0.0.1"
authors = ["gustin <gustin@mycelium.dev>"]
edition = "2018"

[dependencies]
rand = "*"
ed25519-dalek = "1.0.0-pre.1"
blake = "2.0.0"
ocelot = { git = "https://github.com/GaloisInc/ocelot.git", rev = "0.3.1" }
